// Count values array items
const valueLines = `
data.deviceId,
data.location,
data.timestamp,
data.data.Hydrostatic_Value,
data.data.DryRunAlert,
data.data.HighLevelFloatAlert,
data.data.Pump_1_Manual,
data.data.Pump_2_Manual,
data.data.Pump_1_Auto,
data.data.Pump_2_Auto,
data.data.Pump_1_Protection,
data.data.Pump_2_Protection,
data.data.Pump_1_Contactor_Feedback,
data.data.Pump_2_Contactor_Feedback,
data.data.POWER_1_R,
data.data.POWER_1_Y,
data.data.POWER_1_B,
data.data.IRMS_1_R,
data.data.IRMS_1_Y,
data.data.IRMS_1_B,
data.data.POWER_2_R,
data.data.POWER_2_Y,
data.data.POWER_2_B,
data.data.IRMS_2_R,
data.data.IRMS_2_Y,
data.data.IRMS_2_B,
data.data.VRMS_1_R,
data.data.VRMS_1_Y,
data.data.VRMS_1_B,
data.data.VRMS_2_R,
data.data.VRMS_2_Y,
data.data.VRMS_2_B,
data.data.VAHR_1_R,
data.data.VAHR_1_Y,
data.data.VAHR_1_B,
data.data.VAHR_2_R,
data.data.VAHR_2_Y,
data.data.VAHR_2_B,
data.data.FREQ_1_R,
data.data.FREQ_1_Y,
data.data.FREQ_1_B,
data.data.FREQ_2_R,
data.data.FREQ_2_Y,
data.data.FREQ_2_B,
data.data.RHS_1,
data.data.RHS_2,
JSON.stringify(data)
`;

const values = valueLines.split('\n').map(v => v.trim()).filter(v => v && !v.startsWith('//'));
console.log('Values array count:', values.length);
console.log(values);
